# Generated by Django 2.2.24 on 2021-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_customer_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomergroupdata',
            name='customer_group_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercustomergroupdata',
            name='customer_group_name_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercustomergroupdata',
            name='customer_group_name_sv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
