# Generated by Django 2.2.24 on 2021-11-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_translation_options_to_ocgd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='name_fi',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
    ]
