sudo: required
dist: xenial

services:
  - docker

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8-dev'
node_js: 'lts/*'

matrix:
  allow_failures:
  - python: 3.8-dev

cache: pip

# Respa uses int4range (IntegerRangeField) so needs at least Postgres9.2
# As of 2017-08 the new travis trusty images have broken postgis,
# so we have to specify the exact postgres version to install right addons.
# They also seem to miss the GDAL C library...
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libgdal-dev
      - postgresql-9.6-postgis-2.4

before_install:
  - chmod -R +x .
  - psql template1 -c 'CREATE EXTENSION IF NOT EXISTS hstore;'
  - psql template1 -c 'CREATE EXTENSION IF NOT EXISTS postgis;'
  - psql -c 'create database respa;' -U postgres
  - pip install codecov -r requirements.txt

before_script:
  - ./build-resources
  - ls -l respa_admin/static/respa_admin/main.css  # Check main.css got built
  - ./manage.py compilemessages
  - ./manage.py makemigrations account admin auth authtoken caterings contenttypes easy_thumbnails guardian kulkunen munigeo notifications resources respa_exchange reversion sessions sites socialaccount tkusers users #comments app fails because lambda cannot be serialized.
  - ./manage.py migrate

script: pytest --cov . --doctest-modules

after_success:
  - codecov
  - ./deploy/containerize.sh

notifications:
  slack:
    secure: ZKyHnLucb1UKKSIG0fQQnsVjk7P4IcxyHIoNtUqK5/3vPAUe4DFlLVeCzKZewVmhbXfK9tmZ3Go2dFgwVaZCUAzNZEqUq306YS9otFmzbSdfv6kweJSKuL9Vf7qSHf1m9M0wFja8t80lDkVFbnQCC3S866q7/BYzGxduLzL063RRB6TtAwg0lPdLxGthv/9sOdcF6SQAZ+xySAjDcBlN4lCMD8IG2iMNE1doA9r43dr+ylNXUO1L6oxRRINODqW1ek9A4TiU9yMQ7Raf6Y+cPtLsDadTWXaooBOkvSERzVfFxjNu9EV8hUgLO25azXrP8VAy1f3vPVs9cggi7j93KCMJjfXrh3YPj2AviiUCiX0aRh4Y+V7fez797iwJzsfhlfhiHK9Twj30JoHX9dGqcgS2F+tG+uOnaC2BfzLf0TO/kePQ1L/TRN0slldKTSR03Nd6wxb7Zr8HtjC8PU50oTvsLJHSGUUr6Yw7tppgzCBzlgjhATHw1DXlUnLQz00np+Z8fzDChbsos0PiPtQrc4Kqn74j6al8ggzEWrXUnrTlFUsQCRdli9gNfqkgSBfm058fV8mckOsRegLs/qLSFzKOv4MpF2/VyPvWCtxl+9Ixhs5mjDPKYOwKetk212EKAR89e13MmyjGN4szvBFZcGnXoDPFvxxEtepG6ix40no=
