services:
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_URL: postgis://respa:respa@database:5432/respa
    volumes:
      - .:/srv/app
      - static-files:/var/www/static/
    ports:
      - 8000:8000
    depends_on:
      - database
    container_name: respa-api
    extra_hosts:
      - "database:172.17.0.1"

volumes:
  static-files: {}