services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./docker-compose.env

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db_respa_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - ./docker-compose.env

volumes:
  db_respa_data: