using 'template.bicep'

var prefix = readEnvironmentVariable('RESOURCE_PREFIX')
var sanitizedPrefix = replace(prefix, '-', '')
param apiImageName = 'api'
param uiImageName = 'ui'
param apiUrl = 'https://testirespa.turku.fi'
param apiWebAppName = '${prefix}-api'
param uiWebAppName = '${prefix}-ui'
param appInsightsName = '${prefix}-appinsights'
param cacheName = '${prefix}-cache'
param containerRegistryName = '${sanitizedPrefix}registry'
param dbName = 'respa_development_jenkins'
param dbServerName = '${prefix}-db'
param dbAdminUsername = 'turkuadmin'
param dbUsername = 'respa'
param keyvaultName = '${sanitizedPrefix}-kv'
param serverfarmPlanName = 'serviceplan'
param storageAccountName = '${sanitizedPrefix}store'
param apiOutboundIpName = 'turku-test-respa-outbound-ip'
param natGatewayName = '${prefix}-nat'
param vnetName =  '${prefix}-vnet'
param workspaceName = '${prefix}-workspace'
param timmiUsername = 'roLFYzfZC/YcKVG1fq49SvgjvNwi6EVM9EPjY6/rxYU='
param qualitytoolUsername = 'fbf1b51b-5378-459f-8b44-e502d222e13f:turku-testivaraamo-qat-api'
param qualitytoolSftpUsername = 'sftp-varaamo'
