# Generated by Django 2.2.21 on 2021-06-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0001_create_accessibility_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshortage',
            name='shortage',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='serviceshortage',
            name='shortage_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='serviceshortage',
            name='shortage_fi',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='serviceshortage',
            name='shortage_sv',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
