# Generated by Django 2.2.11 on 2020-08-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0121_add_has_arrived_field'),
        ('resources', '0121_auto_20200825_1800'),
    ]

    operations = [
    ]
