# Generated by Django 2.2.18 on 2021-04-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0125_add_timmi_payload_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='send_sms_notification',
            field=models.BooleanField(blank=True, default=False, help_text='Send SMS notification after reservation', verbose_name='Send SMS notification'),
        )
    ]
