# Generated by Django 3.2.23 on 2024-01-30 14:17

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0152_create_resource_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceequipment',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
